name: Create and publish docker image
on:
 workflow_call:
  inputs:
   image_name:
    required: true
    type: string
   tag: 
    type: string
  secrets:
   registery_username:
    required: true
   registery_password:
    required: true
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
   - name: checkout code
     uses: actions/checkout@v4
   - name: setup docker
     uses: docker/buildX@v1
   - name: Docker login
     uses: docker/login-action@v1
     with:
      username: ${{ secrets.registry_username}}
      password: ${{ secrets.registry_password}}
      
     
     
   
