name: Create and publish docker image
on:
 workflow_call:
  inputs:
   image_name:
    required: true
    type: string
   tag: 
    type: string
  secrets:
   registry_username:
    required: true
   registry_password:
    required: true
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
   - name: checkout code
     uses: actions/checkout@v4
   - name: setup docker
     uses: docker/setup-buildx-action@v1
   - name: Docker login
     uses: docker/login-action@v1
     with:
      username: ${{ secrets.registry_username}}
      password: ${{ secrets.registry_password}}
   - name: Build and push
     uses: docker/build-push-action@v6
     with:
      push: true
      context: .
      file: ./Dockerfile 
      tags: mkshahi/reusable:latest
      
     
     
     
   
