name: Create and publish docker image
on:
 workflow_call:
  inputs:
   image_name:
    required: true
    type: string
   tag: 
    type: string
  secrets:
   registery_username:
    required: true
   registery_password:
    required: true
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
   - name: checkout code
     uses: actions/checkout@v4
   - name: setup docker
     uses: docker/buildx
