name: resuable workflow user
on:
 workflow_dispatch:
jobs:
 do-it:
  runs-on: ubuntu-latest
  steps:
  - name: code checkout
    uses: actions/checkout@v3
  - name: Run oneline script
    run: echo Hello, world
 docker-job:
  uses:  mkshahi/resusableworkflow/.github/workflows/buildAndPublishDockerimage.yml@main
  with:
   image_name: nginx
  secrets:
  
   registry_username: ${{ secrets.registry_username}}
   registry_password: ${{ secrets.registry_password}}
  
  
 
